### ISSUE TITLE
Thanks for moving my repo to Github

### ISSUE THREAD

**Issue by Darelbi** [ViteFalcon/infectorpp#13]
Since I don't know how long will take for version 2 to become published I just putted a notice that official repo for version 1 is now the one you moved here :D

I'll keep an eye to give some help or to integrate forward some stuff in v2 :)

Thanks!

**Comment by ViteFalcon** [comment]
Thanks for that Darelbi! I have no problem maintaining V1. I'll try to improve it and possibly take some from yours, if possible. There are a bunch of features I would like to add. I'll create issues for them here and will let you know about them :+1:
